# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Sakiru Akinpelu | Data Analyst & Automation Specialist
first_name: Sakiru
middle_name: A.
last_name: Akinpelu
contact_note: >
  The best way to reach me is via email. I respond within 24 hours to all collaboration and project inquiries.
description: >
  Portfolio of Sakiru Akinpelu — a Data Analyst and Workflow Automation Specialist passionate about data-driven decision making, 
  process automation, and business intelligence. I transform raw data into actionable insights using tools like Power BI, Excel, SQL, 
  and Python, while also building smart automations to save time and improve efficiency.
footer_text: >
  © 2025 Sakiru Akinpelu. Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> 
  with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme. 
  Hosted on <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

keywords: data analysis, workflow automation, Power BI, SQL, Zapier, Excel, Python, data visualization, process improvement
lang: en
icon: 📊

url: https://sakiruakinpelu.github.io  # base hostname
baseurl: /Portfolio  # replace with your repo name if different
last_updated: true
back_to_top: true

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------
repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed

# -----------------------------------------------------------------------------
# Analytics and Verification
# -----------------------------------------------------------------------------
google_analytics: G-XXXXXXXXXX  # Add your GA ID later if you want to track visits
google_site_verification:
bing_site_verification:

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Insights & Automations
blog_description: Sharing thoughts on data analytics, workflow automation, and productivity tools.
permalink: /blog/:year/:title/
pagination:
  enabled: true
related_blog_posts:
  enabled: true
  max_related: 5

# -----------------------------------------------------------------------------
# Social Links (add to top navbar)
# -----------------------------------------------------------------------------
enable_navbar_social: true

social:
  email: sakiruakinpelu@gmail.com
  linkedin: sakiru-akinpelu
  github: sakiruakinpelu
  twitter: sakiru_akinpelu
  medium: sakiruakinpelu
  kaggle: sakiruakinpelu
  upwork: sakiru-akinpelu

# -----------------------------------------------------------------------------
# Newsletter / Contact CTA (optional)
# -----------------------------------------------------------------------------
newsletter:
  enabled: false

# -----------------------------------------------------------------------------
# Projects and Categories
# -----------------------------------------------------------------------------
enable_project_categories: true

collections:
  projects:
    output: true
  news:
    defaults:
      layout: post
    output: true
  books:
    output: true
